from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

from plate_hog_svm.config import SVMTrainConfig
from plate_hog_svm.dataset import load_labeled_samples
from plate_hog_svm.features import HOGFeatureExtractor
from plate_hog_svm.training import (
    build_metadata,
    evaluate_classifier,
    limit_negatives,
    save_model_and_metadata,
    stratified_split,
    tune_and_train,
)
from plate_hog_svm.visualization import (
    load_labeled_preview_samples,
    save_feature_embedding_plot,
    save_hog_visualization_grid,
)


def parse_float_list(value: str) -> tuple[float, ...]:
    values = tuple(float(v.strip()) for v in value.split(",") if v.strip())
    if not values:
        raise ValueError("Expected at least one C value")
    return values


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Class 1: Extract HOG features, normalize with StandardScaler, "
            "tune C via RandomizedSearchCV, train LinearSVM, "
            "evaluate with precision/recall/F1/confusion-matrix."
        ),
    )
    # Data
    parser.add_argument(
        "--labels",
        default="outputs/labels.csv",
        help="CSV with image path column and label column.",
    )
    parser.add_argument(
        "--hard-negatives",
        default="",
        help=(
            "CSV generated by mine_hard_negatives.py containing hard negative crops "
            "(label=0/-1). Will be merged into the training set if provided."
        ),
    )
    # Model output
    parser.add_argument(
        "--model",
        default="models/plate_svm.joblib",
        help="Output path for sklearn Pipeline (.joblib).",
    )
    parser.add_argument(
        "--metadata",
        default="",
        help="Output path for metadata JSON. Defaults to model path with .json extension.",
    )
    # Split
    parser.add_argument(
        "--val-ratio",
        type=float,
        default=0.2,
        help="Validation split ratio per class (default 0.2).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed.",
    )
    parser.add_argument(
        "--max-negatives",
        type=int,
        default=0,
        help="Cap on negative samples. 0 = keep all.",
    )
    # Diagnostics before LinearSVM training
    parser.add_argument(
        "--hog-visualization",
        default="outputs/visualize/hog_visualization.png",
        help=(
            "Output image for skimage HOG visualize=True grid. "
            "Use an empty string to disable."
        ),
    )
    parser.add_argument(
        "--hog-visualization-limit",
        type=int,
        default=12,
        help="Max labeled crops to include in the HOG visualization grid.",
    )
    parser.add_argument(
        "--feature-plot",
        default="outputs/visualize/hog_feature_embedding.png",
        help=(
            "Output scatter plot for HOG features reduced before LinearSVM training. "
            "Use an empty string to disable."
        ),
    )
    parser.add_argument(
        "--feature-plot-method",
        choices=["pca", "tsne"],
        default="pca",
        help="Dimensionality reduction method for the HOG scatter plot.",
    )
    parser.add_argument(
        "--feature-plot-dims",
        type=int,
        choices=[2, 3],
        default=2,
        help="Scatter plot dimensions: 2 or 3.",
    )
    parser.add_argument(
        "--feature-plot-sample",
        type=int,
        default=2000,
        help="Max HOG samples to draw in the feature scatter plot. 0 = all.",
    )
    # Hyperparameter search
    parser.add_argument(
        "--c-values",
        default="0.001,0.01,0.1,1.0,10.0,100.0",
        help="Comma-separated C values for RandomizedSearchCV.",
    )
    parser.add_argument(
        "--search-n-iter",
        type=int,
        default=20,
        help="Number of iterations for RandomizedSearchCV.",
    )
    parser.add_argument(
        "--cv-folds",
        type=int,
        default=5,
        help="Number of cross-validation folds.",
    )
    parser.add_argument(
        "--scoring",
        default="f1",
        choices=["f1", "f1_macro", "precision", "recall", "accuracy"],
        help="Metric to optimize during search (default: f1).",
    )
    parser.add_argument(
        "--max-iter",
        type=int,
        default=10000,
        help="Max iterations for LinearSVM.",
    )
    parser.add_argument(
        "--class-weight",
        choices=["balanced", "none"],
        default="balanced",
        help="Class weighting for LinearSVM. Use 'none' if you already balanced the dataset manually.",
    )
    return parser.parse_args()


def print_metrics(metrics: dict, split_name: str = "Val") -> None:
    """Print evaluation metrics to console."""
    if not metrics.get("samples"):
        print(f"{split_name}: skipped (empty split)")
        return

    print(f"\n{'=' * 60}")
    print(f"  {split_name} Metrics  ({metrics['samples']} samples)")
    print(f"{'=' * 60}")
    print(f"  Accuracy  : {metrics['accuracy']:.4f}")
    print(f"  Precision : {metrics['precision']:.4f}  (plate class)")
    print(f"  Recall    : {metrics['recall']:.4f}  (plate class)")
    print(f"  F1        : {metrics['f1']:.4f}  (plate class)")
    print(f"  F1 macro  : {metrics['f1_macro']:.4f}")
    print()
    cm = metrics["confusion_matrix"]
    print("  Confusion Matrix (rows=actual, cols=predicted):")
    print(f"             non_plate  plate")
    print(f"  non_plate  {cm[0][0]:>9}  {cm[0][1]:>5}")
    print(f"  plate      {cm[1][0]:>9}  {cm[1][1]:>5}")
    print(f"  -> TP={metrics['tp']}  TN={metrics['tn']}  FP={metrics['fp']}  FN={metrics['fn']}")
    print()
    print("  Classification Report:")
    for line in metrics["classification_report"].splitlines():
        print(f"    {line}")
    print(f"{'=' * 60}")


def main() -> int:
    args = parse_args()

    labels_path = Path(args.labels)
    if not labels_path.exists():
        print(f"Labels CSV not found: {labels_path}", file=sys.stderr)
        return 1

    extractor = HOGFeatureExtractor()

    print(f"\n[1/4] Loading and extracting HOG features from {labels_path} ...")
    try:
        x, y, stats = load_labeled_samples(labels_path, extractor)
    except Exception as exc:
        print(f"Dataset load failed: {exc}", file=sys.stderr)
        return 1

    print(f"      Total: {stats.samples}  (pos={stats.positives}, neg={stats.negatives}, skip={stats.skipped})")

    # Merge hard negatives if provided
    visualization_label_paths = [labels_path]
    if args.hard_negatives:
        hn_path = Path(args.hard_negatives)
        if hn_path.exists():
            print(f"[1b]  Merging hard negatives from {hn_path} ...")
            try:
                x_hn, y_hn, hn_stats = load_labeled_samples(
                    hn_path,
                    extractor,
                    require_both_classes=False,
                )
                x = np.vstack([x, x_hn])
                y = np.concatenate([y, y_hn])
                print(f"      +{hn_stats.samples} hard negative samples added")
                visualization_label_paths.append(hn_path)
            except Exception as exc:
                print(f"      Warning: skipping hard negatives: {exc}", file=sys.stderr)
        else:
            print(f"      Warning: --hard-negatives path not found: {hn_path}", file=sys.stderr)

    # Visualize a few HOG images with skimage.feature.hog(..., visualize=True).
    if args.hog_visualization:
        hog_vis_path = Path(args.hog_visualization)
        print(f"[1c]  Writing HOG visualization to {hog_vis_path} ...")
        try:
            preview_samples = load_labeled_preview_samples(
                visualization_label_paths,
                max_samples=args.hog_visualization_limit,
            )
            written = save_hog_visualization_grid(preview_samples, extractor, hog_vis_path)
            if written:
                print(f"      HOG visualization samples: {written}")
            else:
                print("      Warning: no preview samples available for HOG visualization")
        except Exception as exc:
            print(f"      Warning: HOG visualization skipped: {exc}", file=sys.stderr)

    # Balance negatives
    x, y = limit_negatives(x, y, args.max_negatives, args.seed)

    # Draw PCA/t-SNE scatter of HOG features before LinearSVM training.
    if args.feature_plot:
        feature_plot_path = Path(args.feature_plot)
        print(
            f"\n[2/5] HOG feature scatter "
            f"({args.feature_plot_method.upper()}, {args.feature_plot_dims}D) ..."
        )
        try:
            plot_info = save_feature_embedding_plot(
                x=x,
                y=y,
                output_path=feature_plot_path,
                method=args.feature_plot_method,
                dims=args.feature_plot_dims,
                sample_size=args.feature_plot_sample,
                seed=args.seed,
            )
            print(f"      Plot      : {feature_plot_path}")
            print(f"      Samples   : {plot_info['samples']}")
            if "explained_variance_ratio" in plot_info:
                variance = ", ".join(f"{v:.4f}" for v in plot_info["explained_variance_ratio"])
                print(f"      PCA var   : {variance}")
            if "perplexity" in plot_info:
                print(f"      t-SNE perp: {plot_info['perplexity']:.2f}")
        except Exception as exc:
            print(f"      Warning: feature scatter skipped: {exc}", file=sys.stderr)

    # Train/val split
    train_idx, val_idx = stratified_split(y, args.val_ratio, args.seed)
    x_train, y_train = x[train_idx], y[train_idx]
    x_val, y_val = x[val_idx], y[val_idx]
    print(f"\n[3/5] Split: train={len(train_idx)}, val={len(val_idx)}")

    # Hyperparameter tuning config
    try:
        c_values = parse_float_list(args.c_values)
    except ValueError as exc:
        print(f"Invalid --c-values: {exc}", file=sys.stderr)
        return 1

    train_config = SVMTrainConfig(
        c_values=c_values,
        search_n_iter=args.search_n_iter,
        cv_folds=args.cv_folds,
        scoring=args.scoring,
        max_iter=args.max_iter,
        class_weight=None if args.class_weight == "none" else args.class_weight,
    )
    print(f"\n[4/5] Tuning + Training (scoring={train_config.scoring}, cv={train_config.cv_folds} folds) ...")
    print(f"      C candidates: {list(train_config.c_values)}")

    try:
        pipeline, search_info = tune_and_train(x_train, y_train, train_config, args.seed)
        metrics = evaluate_classifier(pipeline, x_val, y_val)
        metadata = build_metadata(pipeline, x, y, extractor.config, metrics, search_info, train_config)
    except Exception as exc:
        print(f"Training failed: {exc}", file=sys.stderr)
        return 1

    print_metrics(metrics, split_name="Validation")

    # Save model
    model_path = Path(args.model)
    metadata_path = Path(args.metadata) if args.metadata else None

    print(f"\n[5/5] Saving model ...")
    written_metadata = save_model_and_metadata(pipeline, model_path, metadata, metadata_path)
    print(f"      Model    : {model_path}")
    print(f"      Metadata : {written_metadata}")
    print(f"\nDone!\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
